/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as InterestsIndexRouteImport } from './routes/interests/index'
import { Route as InterestsNewRouteImport } from './routes/interests/new'
import { Route as InterestsInterestIdEditRouteImport } from './routes/interests/$interestId.edit'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsIndexRoute = InterestsIndexRouteImport.update({
  id: '/interests/',
  path: '/interests/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsNewRoute = InterestsNewRouteImport.update({
  id: '/interests/new',
  path: '/interests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsInterestIdEditRoute = InterestsInterestIdEditRouteImport.update({
  id: '/interests/$interestId/edit',
  path: '/interests/$interestId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/interests/new': typeof InterestsNewRoute
  '/interests/': typeof InterestsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/interests/$interestId/edit': typeof InterestsInterestIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/interests/new': typeof InterestsNewRoute
  '/interests': typeof InterestsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/interests/$interestId/edit': typeof InterestsInterestIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/telegram': typeof TelegramRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/interests/new': typeof InterestsNewRoute
  '/interests/': typeof InterestsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/interests/$interestId/edit': typeof InterestsInterestIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/telegram'
    | '/trocar-senha'
    | '/interests/new'
    | '/interests/'
    | '/matches/'
    | '/messages/'
    | '/interests/$interestId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/telegram'
    | '/trocar-senha'
    | '/interests/new'
    | '/interests'
    | '/matches'
    | '/messages'
    | '/interests/$interestId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/telegram'
    | '/trocar-senha'
    | '/interests/new'
    | '/interests/'
    | '/matches/'
    | '/messages/'
    | '/interests/$interestId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TelegramRoute: typeof TelegramRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  InterestsNewRoute: typeof InterestsNewRoute
  InterestsIndexRoute: typeof InterestsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  InterestsInterestIdEditRoute: typeof InterestsInterestIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/': {
      id: '/interests/'
      path: '/interests'
      fullPath: '/interests/'
      preLoaderRoute: typeof InterestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/new': {
      id: '/interests/new'
      path: '/interests/new'
      fullPath: '/interests/new'
      preLoaderRoute: typeof InterestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/$interestId/edit': {
      id: '/interests/$interestId/edit'
      path: '/interests/$interestId/edit'
      fullPath: '/interests/$interestId/edit'
      preLoaderRoute: typeof InterestsInterestIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TelegramRoute: TelegramRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  InterestsNewRoute: InterestsNewRoute,
  InterestsIndexRoute: InterestsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  InterestsInterestIdEditRoute: InterestsInterestIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
